name: mobile_number_input
description: "Customizable widget for entering phone numbers with country code selector."
version: 0.0.1
repository: https://github.com/username/mobile_number_input

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/country/

  plugin:
    platforms:
      android:
        package: com.example.mobile_number_input
        pluginClass: MobileNumberInputPlugin
      ios:
        pluginClass: MobileNumberInputPlugin
